# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-api
  template:
    metadata:
      labels:
        app: ml-api
    spec:
      containers:
      - name: ml-api-container
        image: ml-api:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        # envFrom:
        # - configMapRef:
        #     name: hello-k8s-config # Load all key-value pairs from our ConfigMap as environment variables